/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e.profiling.system;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author PlonGaming
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form AddBarangay
     */
    public MainWindow() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Community e-Profiling System");
        setIconImage();

    }

    AddBarangay ad;
    ListOfAllResidents lr;
    ListOfAllBarangay lb;
    SearchWindow sw;
    AddResident ar;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        nameDisplay = new javax.swing.JTextField();
        positionDisplay = new javax.swing.JTextField();
        imageDisplay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addBarangay = new javax.swing.JMenuItem();
        addResident = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_LOAR = new javax.swing.JMenuItem();
        jMenuItem_LOAB = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_Query = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1054, 775));

        nameDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameDisplay.setBorder(null);

        positionDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        positionDisplay.setForeground(new java.awt.Color(255, 0, 0));
        positionDisplay.setBorder(null);

        imageDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/profiling/system/window.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1860, 980));
        jLabel1.setMinimumSize(new java.awt.Dimension(1860, 980));
        jLabel1.setPreferredSize(new java.awt.Dimension(1860, 980));

        jDesktopPane1.setLayer(nameDisplay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(positionDisplay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(imageDisplay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1490, 1490, 1490)
                        .addComponent(positionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1690, 1690, 1690)
                        .addComponent(imageDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1490, 1490, 1490)
                        .addComponent(nameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(positionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imageDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 51, 51));

        jMenu1.setText("Add");

        addBarangay.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        addBarangay.setText("Add Barangay");
        addBarangay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBarangayMouseClicked(evt);
            }
        });
        addBarangay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBarangayActionPerformed(evt);
            }
        });
        jMenu1.add(addBarangay);

        addResident.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        addResident.setText("Add Residents");
        addResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResidentActionPerformed(evt);
            }
        });
        jMenu1.add(addResident);

        exitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem_LOAR.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_LOAR.setText("List of ALL Residents");
        jMenuItem_LOAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LOARActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_LOAR);

        jMenuItem_LOAB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_LOAB.setText("List of ALL Barangay");
        jMenuItem_LOAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LOABActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_LOAB);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Query");

        jMenuItem_Query.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Query.setText("Search Residents");
        jMenuItem_Query.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_QueryActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Query);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResidentActionPerformed
        try {
            if (ar == null || ar.isClosed()) {
                ar = new AddResident();
                jDesktopPane1.add(ar);
                ar.setVisible(true);
                ar.setSelected(true);
            } else {
                if (ar.isIcon()) {
                    this.ar.setIcon(false);
                }
                ar.setSelected(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_addResidentActionPerformed

    private void addBarangayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBarangayActionPerformed

        try {
            if (ad == null || ad.isClosed()) {
                ad = new AddBarangay();
                jDesktopPane1.add(ad);
                ad.setVisible(true);
                ad.setSelected(true);
            } else {
                if (ad.isIcon()) {
                    this.ad.setIcon(false);
                }
                ad.setSelected(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_addBarangayActionPerformed

    private void addBarangayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBarangayMouseClicked

    }//GEN-LAST:event_addBarangayMouseClicked

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Logout?", "Community e-Profiling System",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (reply == JOptionPane.YES_OPTION) {
            Login log = new Login();
            dispose();
            log.setVisible(true);
        } else {

        }
    }//GEN-LAST:event_exitMenuActionPerformed

    private void jMenuItem_LOARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LOARActionPerformed
        ListOfAllResidents loar;
        try {
            loar = new ListOfAllResidents();
            loar.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem_LOARActionPerformed

    private void jMenuItem_LOABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LOABActionPerformed
        ListOfAllBarangay loab = new ListOfAllBarangay();
        loab.setVisible(true);
    }//GEN-LAST:event_jMenuItem_LOABActionPerformed

    private void jMenuItem_QueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_QueryActionPerformed
        SearchWindow sw;
        try {
            sw = new SearchWindow();
            sw.displayName.setText(nameDisplay.getText());
            sw.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem_QueryActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainWindow().setVisible(true);
//            }
//        });
//    }
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBarangay;
    private javax.swing.JMenuItem addResident;
    private javax.swing.JMenuItem exitMenu;
    public javax.swing.JLabel imageDisplay;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_LOAB;
    private javax.swing.JMenuItem jMenuItem_LOAR;
    private javax.swing.JMenuItem jMenuItem_Query;
    public javax.swing.JTextField nameDisplay;
    public javax.swing.JTextField positionDisplay;
    // End of variables declaration//GEN-END:variables
//public void searchImage2() {
//        String search = nameDisplay.getText();
//
//        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rcceps", "root", "");
//            String sql = "SELECT `acc_image` FROM `accounts` WHERE acc_fullname = '" + search + "'";
//            PreparedStatement pst = con.prepareStatement(sql);
//            ResultSet rs = pst.executeQuery();
//
//            if (rs.next()) {
//                byte[] image = rs.getBytes("acc_image");
//                ImageIcon image1 = new ImageIcon(image);
//                Image mm = image1.getImage();
//                Image img = mm.getScaledInstance(imgDisplay.getWidth(), imgDisplay.getHeight(), Image.SCALE_SMOOTH);
//                ImageIcon image2 = new ImageIcon(img);
//                imgDisplay.setIcon(image2);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
//    }
}
